Repository UmiNetwork/op-move, pull requests merged in 2025-04, with the labels that each got.

#319 Feat(evm-native): Ensure base token balance changes on EVM are reflected on Move
  api/src/methods/forkchoice_updated.rs
  api/src/methods/get_payload.rs
  api/src/methods/mod.rs
  app/src/actor.rs
  blockchain/src/state/read.rs
  evm-ext/src/events.rs
  evm-ext/src/native_evm_context.rs
  evm-ext/src/native_impl.rs
  execution/src/canonical.rs
  execution/src/deposited.rs
  execution/src/eth_token.rs
  execution/src/lib.rs
  execution/src/nonces.rs
  execution/src/simulate.rs
  execution/src/tag_validation.rs
  execution/src/tests/gas_cost.rs
  execution/src/tests/natives.rs
  execution/src/tests/utils.rs
  server/src/tests/integration.rs
Labels: transactions

#330 Chore(deps): Upgrade to Aptos v1.27.2
  Cargo.lock
  Cargo.toml
  api/src/methods/get_payload.rs
  app/src/actor.rs
  blockchain/src/state/read.rs
  evm-ext/src/events.rs
  evm-ext/src/native_evm_context.rs
  evm-ext/src/solidity_abi.rs
  evm-ext/src/state_changes.rs
  evm-ext/src/type_utils.rs
  execution/Cargo.toml
  execution/src/canonical.rs
  execution/src/deposited.rs
  execution/src/eth_token.rs
  execution/src/execute.rs
  execution/src/lib.rs
  execution/src/nonces.rs
  execution/src/simulate.rs
  execution/src/tag_validation.rs
  execution/src/tests/data_type.rs
  execution/src/tests/erc20.rs
  execution/src/tests/evm_native.rs
  execution/src/tests/framework.rs
  execution/src/tests/gas_cost.rs
  execution/src/tests/mod.rs
  execution/src/tests/natives.rs
  execution/src/tests/res/withdrawal-script/Move.toml
  execution/src/tests/utils.rs
  genesis-builder/src/main.rs
  genesis-image/build.rs
  genesis/Cargo.toml
  genesis/aptos.mrb
  genesis/src/config.rs
  genesis/src/framework.rs
  genesis/src/lib.rs
  genesis/src/vm.rs
  server/src/lib.rs
  server/src/tests/integration.rs
  server/src/tests/integration/erc20.rs
  state/Cargo.toml
  state/src/lib.rs
  storage/heed/Cargo.toml
  storage/heed/src/state.rs
  storage/rocksdb/Cargo.toml
  storage/rocksdb/src/state.rs
Labels: devops

#331 refactor(app): Separate all application scenarios from `StateActor` into `Application`
  api/src/methods/get_payload.rs
  api/src/methods/mod.rs
  api/src/methods/new_payload.rs
  app/src/actor.rs
  app/src/command.rs
  app/src/dependency.rs
  app/src/lib.rs
  app/src/query.rs
  app/src/tests.rs
  server/src/lib.rs
Labels: storage

#337 Chore(deps): updrade crossbeam-channel to v0.5.15
  Cargo.lock
Labels: devops

#336 Feat(transactions): Properly charge gas for natives (including EVM)
  api/src/methods/estimate_gas.rs
  api/src/methods/get_payload.rs
  app/src/command.rs
  app/src/query.rs
  app/src/tests.rs
  blockchain/src/state/read.rs
  evm-ext/src/native_impl.rs
  execution/src/canonical.rs
  execution/src/deposited.rs
  execution/src/eth_token.rs
  execution/src/lib.rs
  execution/src/nonces.rs
  execution/src/simulate.rs
  execution/src/tag_validation.rs
  execution/src/tests/evm_native.rs
  execution/src/tests/gas_cost.rs
  execution/src/tests/natives.rs
  execution/src/tests/transfer.rs
  execution/src/tests/utils.rs
  genesis-image/build.rs
  genesis/src/config.rs
  genesis/src/framework.rs
  genesis/src/vm.rs
  server/src/lib.rs
Labels: transactions, gas

#335 feat(app): Implement parallel queries
  api/src/methods/block_number.rs
  api/src/methods/call.rs
  api/src/methods/chain_id.rs
  api/src/methods/estimate_gas.rs
  api/src/methods/fee_history.rs
  api/src/methods/forkchoice_updated.rs
  api/src/methods/get_balance.rs
  api/src/methods/get_block_by_hash.rs
  api/src/methods/get_block_by_number.rs
  api/src/methods/get_nonce.rs
  api/src/methods/get_payload.rs
  api/src/methods/get_proof.rs
  api/src/methods/get_transaction_by_hash.rs
  api/src/methods/get_transaction_receipt.rs
  api/src/methods/mod.rs
  api/src/methods/new_payload.rs
  api/src/methods/send_raw_transaction.rs
  api/src/request.rs
  app/src/actor.rs
  app/src/input.rs
  app/src/query.rs
  app/src/tests.rs
  server/src/dependency/heed.rs
  server/src/dependency/in_memory.rs
  server/src/dependency/rocksdb.rs
  server/src/lib.rs
  server/src/tests/get_proof.rs
Labels: api

#340 build(docker): Parse rust toolchain from workspace file
  docker/Dockerfile.op-move
Labels: devops

#341 feat: Shut the server down if command queue panics
  api/src/json_utils.rs
  api/src/jsonrpc.rs
  api/src/methods/forkchoice_updated.rs
  api/src/methods/get_payload.rs
  api/src/methods/get_transaction_by_hash.rs
  api/src/methods/get_transaction_receipt.rs
  api/src/methods/mod.rs
  api/src/methods/new_payload.rs
  api/src/methods/send_raw_transaction.rs
  api/src/request.rs
  app/src/factory.rs
  app/src/lib.rs
  app/src/queue.rs
  server/src/lib.rs
  server/src/main.rs
  server/src/tests/get_proof.rs
  server/src/tests/integration.rs
Labels: api

#339 Feat(genesis): automatically bridge Superchain tokens
  Cargo.lock
  api/src/methods/get_payload.rs
  evm-ext/src/lib.rs
  evm-ext/src/native_evm_context.rs
  evm-ext/src/native_impl.rs
  evm-ext/src/state_changes.rs
  execution/src/tests/res/bridged_tokens_test.json
  genesis/Cargo.toml
  genesis/src/bridged_tokens.rs
  genesis/src/config.rs
  genesis/src/lib.rs
Labels: framework

#343 Refactor(sdk): Repackage under @moved
  sdk/hardhat-moved/package.json
  sdk/hardhat-moved/yarn.lock
Labels: sdk

#342 Fix(tx): Return only values from call without layout
  api/src/methods/call.rs
  evm-ext/src/events.rs
  evm-ext/src/lib.rs
  execution/src/simulate.rs
  server/src/tests/integration/erc20.rs
Labels: sdk

#344 Fix(docker): Copy bridged token file
  docker/Dockerfile.op-move
Labels: bug

#348 perf(app): Remove `UpdateHead` command
  api/src/methods/forkchoice_updated.rs
  api/src/methods/get_payload.rs
  api/src/methods/mod.rs
  app/src/actor.rs
  app/src/command.rs
  app/src/input.rs
  app/src/tests.rs
  server/src/lib.rs
Labels: transactions

#345 test: Add benchmark for command queue size
  Cargo.lock
  Cargo.toml
  server/Cargo.toml
  server/benches/perf/main.rs
  server/benches/perf/queue/input.rs
  server/benches/perf/queue/mod.rs
  server/benches/perf/queue/tests.rs
Labels: devops

#349 Feat(evm): allow all users to deploy EVM contracts
  api/src/methods/get_payload.rs
  app/src/block_hash.rs
  app/src/command.rs
  app/src/lib.rs
  app/src/query.rs
  app/src/tests.rs
  blockchain/src/state/read.rs
  evm-ext/src/lib.rs
  evm-ext/src/native_evm_context.rs
  evm-ext/src/native_impl.rs
  evm-ext/src/solidity_abi.rs
  evm-ext/src/state/block_hash.rs
  evm-ext/src/state/mod.rs
  evm-ext/src/state_changes.rs
  evm-ext/src/type_utils.rs
  execution/src/canonical.rs
  execution/src/deposited.rs
  execution/src/eth_token.rs
  execution/src/execute.rs
  execution/src/lib.rs
  execution/src/nonces.rs
  execution/src/simulate.rs
  execution/src/tag_validation.rs
  execution/src/tests/evm_native.rs
  execution/src/tests/mod.rs
  execution/src/tests/natives.rs
  execution/src/tests/utils.rs
  execution/src/transaction.rs
  genesis-builder/framework/evm/sources/Evm.move
  genesis/aptos.mrb
  genesis/src/bridged_tokens.rs
  genesis/src/config.rs
  server/src/tests/evm_contracts.rs
  server/src/tests/get_proof.rs
  server/src/tests/integration.rs
  server/src/tests/mod.rs
  server/src/tests/test_context.rs
  shared/src/error.rs
Labels: framework
