Repository UmiNetwork/op-move, pull requests merged in 2025-02, with the labels that each got.

#271 feat(storage): Implement `StateQueries` using `rocksdb`
  moved/src/state_actor.rs
  moved/src/state_actor/queries.rs
  server/src/dependency.rs
  server/src/lib.rs
  storage/src/all.rs
  storage/src/generic.rs
  storage/src/lib.rs
  storage/src/state.rs
Labels: storage

#280 Feat(server): Health check response on GET requests
  server/src/lib.rs
Labels: api

#284 build(docker): Ignore volumes directory from the docker build context
  .dockerignore
Labels: devops
